name: Publish Palmetto Test
on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building!"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - run: gcloud auth configure-docker

      - name: Build React App
        run: |-
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/palmetto-test . \
          --build-arg WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} \
          --build-arg GOOGLE_API_KEY=${{ secrets.GOOGLE_MAPS_KEY }} 
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/palmetto-test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying!"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy React app
        run: |-
          gcloud run deploy palmetto-test \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/palmetto-test \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
